enum GetxKeys {
  USER_CONTROLLER,
  PRODUCT_DETAILS_CONTROLLER,
  FAVORITES_CONTROLLER,
  CART_PAGE_CONTROLLER,
  HOME_PAGE_CONTROLLER,
  CATEGORY_DETAILS_CONTOLLER,
  COMPLETE_ORDER_CONTROLLER,
  ORDER_DETAILS_CONTROLLER
}